### ISSUE TITLE
Не удаётся загрузить модель

### ISSUE THREAD

**Issue by potassium-chloride** [sberbank-ai/ru-clip#25]
Я использую Python 3.10 на Линуксе и получил такую ошибку:
```
Python 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ruclip
>>> ruclip.__version__
'0.0.2'
>>> clip, processor = ruclip.load("ruclip-vit-base-patch32-384", device="cpu")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dolgikh/anaconda3/envs/GigaAM/lib/python3.10/site-packages/ruclip/__init__.py", line 74, in load
    cached_download(config_file_url, cache_dir=cache_dir, force_filename=filename, use_auth_token=use_auth_token)
  File "/home/dolgikh/anaconda3/envs/GigaAM/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 358, in cached_download
    raise OSError(
OSError: Distant resource does not have an ETag, we won't be able to reliably ensure reproducibility.
>>>
```
Как это исправить?

**Comment by potassium-chloride** [comment]
Удалось исправить обновлением:
```
pip install huggingface-hub==0.23.3
```
У вас requirements.txt старый, надо поправить
